runtime: php82
env: flex

runtime_config: document_root: public

skip_files:
  - .env

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 100

env_variables:
  APP_DEBUG: false
  APP_ENV: production
  APP_KEY: base64:kgndp6jKMZzRVIPPfd/7O3n4KScirTvbqldzDfQqrI8=
  APP_NAME: PeoplePsyche

  LOG_LEVEL: debug
